// Generated by raster-plugin-link. Do not edit.
import Foundation

public enum RasterPlugins {
    public static func registerAll() {
        CameraPlugin.register()
        ClipboardPlugin.register()
        FilesystemPlugin.register()
        HapticsPlugin.register()
    }
}