import fs from "node:fs/promises";
import path from "node:path";

export interface PluginManifest {
  name: string;
  npm?: string;
  ios?: { pod?: string; register?: string };
  android?: { package?: string; register?: string };
  permissions?: {
    ios?: { usageDescriptions?: Record<string, string> };
    android?: string[];
  };
}

export interface LinkPluginsOptions {
  root: string;
  iosDir?: string;
  androidDir?: string;
}

export interface LinkResult {
  plugins: PluginManifest[];
  iosRegisterFile?: string;
  androidRegisterFile?: string;
}

export async function discoverPlugins(root: string): Promise<PluginManifest[]> {
  const manifests: PluginManifest[] = [];
  const configPath = path.join(root, "raster-plugins.json");
  try {
    const config = JSON.parse(await fs.readFile(configPath, "utf8")) as { plugins?: string[] };
    for (const entry of config.plugins ?? []) {
      const manifest = await readManifest(path.resolve(root, entry));
      if (manifest != null) manifests.push(manifest);
    }
  } catch {
    // optional app-level config
  }

  const nodeModules = path.join(root, "node_modules");
  for (const scope of ["@raster"]) {
    const scopeDir = path.join(nodeModules, scope);
    try {
      const entries = await fs.readdir(scopeDir, { withFileTypes: true });
      for (const entry of entries) {
        if (!entry.isDirectory() || !entry.name.startsWith("raster-plugin-")) continue;
        const manifest = await readManifest(path.join(scopeDir, entry.name));
        if (manifest != null) manifests.push(manifest);
      }
    } catch {
      // scope may not exist
    }
  }

  const seen = new Set<string>();
  return manifests.filter((manifest) => {
    if (seen.has(manifest.name)) return false;
    seen.add(manifest.name);
    return true;
  });
}

async function readManifest(packageDir: string): Promise<PluginManifest | null> {
  try {
    const raw = await fs.readFile(path.join(packageDir, "plugin.json"), "utf8");
    return JSON.parse(raw) as PluginManifest;
  } catch {
    return null;
  }
}

export async function linkPlugins(options: LinkPluginsOptions): Promise<LinkResult> {
  const plugins = await discoverPlugins(options.root);
  const result: LinkResult = { plugins };

  if (options.iosDir != null) {
    const swift = renderIosRegister(plugins);
    const filePath = path.join(options.iosDir, "RasterPlugins.generated.swift");
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, swift, "utf8");
    result.iosRegisterFile = filePath;
  }

  if (options.androidDir != null) {
    const kotlin = renderAndroidRegister(plugins);
    const filePath = path.join(options.androidDir, "RasterPlugins.generated.kt");
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, kotlin, "utf8");
    result.androidRegisterFile = filePath;
  }

  return result;
}

function renderIosRegister(plugins: PluginManifest[]): string {
  const lines = [
    "// Generated by raster-plugin-link. Do not edit.",
    "import Foundation",
    "",
    "public enum RasterPlugins {",
    "    public static func registerAll() {",
  ];
  for (const plugin of plugins) {
    const call = plugin.ios?.register ?? `${plugin.name}Plugin.register`;
    lines.push(`        ${call}()`);
  }
  lines.push("    }", "}", "");
  return lines.join("\n");
}

function renderAndroidRegister(plugins: PluginManifest[]): string {
  const lines = [
    "// Generated by raster-plugin-link. Do not edit.",
    "package dev.raster.generated",
    "",
    "object RasterPlugins {",
    "    @JvmStatic",
    "    fun registerAll() {",
  ];
  for (const plugin of plugins) {
    const call = plugin.android?.register ?? `${plugin.name}Plugin.register`;
    lines.push(`        ${call}()`);
  }
  lines.push("    }", "}", "");
  return lines.join("\n");
}