// Generated ABI constants for Node 24.3.0 / NODE_MODULE_VERSION 137.
// Regenerate with: v8_compat/tools/abi-generator.cc (CI drift check).

#pragma once

#define RASTER_V8_ABI_PROFILE "node24-abi137"
#define RASTER_V8_NODE_MODULE_VERSION 137
#define RASTER_V8_NODE_VERSION_STRING "24.3.0"

#define RASTER_V8_K_UNDEFINED_VALUE_ROOT_INDEX 4
#define RASTER_V8_K_THE_HOLE_VALUE_ROOT_INDEX 5
#define RASTER_V8_K_NULL_VALUE_ROOT_INDEX 6
#define RASTER_V8_K_TRUE_VALUE_ROOT_INDEX 7
#define RASTER_V8_K_FALSE_VALUE_ROOT_INDEX 8
#define RASTER_V8_K_EMPTY_STRING_ROOT_INDEX 9

#define RASTER_V8_K_FIRST_NONSTRING_TYPE 0x80
#define RASTER_V8_K_ODDBALL_TYPE 0x83
#define RASTER_V8_K_STRING_TYPE 0x7f

#define RASTER_V8_K_FRAME_TYPE_API_CALL_EXIT 18
#define RASTER_V8_K_FRAME_TYPE_API_CONSTRUCT_EXIT 19

#define RASTER_V8_FUNCTION_CALLBACK_K_UNUSED_INDEX 0
#define RASTER_V8_FUNCTION_CALLBACK_K_ISOLATE_INDEX 1
#define RASTER_V8_FUNCTION_CALLBACK_K_CONTEXT_INDEX 2
#define RASTER_V8_FUNCTION_CALLBACK_K_RETURN_VALUE_INDEX 3
#define RASTER_V8_FUNCTION_CALLBACK_K_TARGET_INDEX 4
#define RASTER_V8_FUNCTION_CALLBACK_K_NEW_TARGET_INDEX 5
#define RASTER_V8_FUNCTION_CALLBACK_K_ARGS_LENGTH 6
#define RASTER_V8_FUNCTION_CALLBACK_K_THIS_VALUES_INDEX (-1)

#define RASTER_V8_PROPERTY_CALLBACK_K_KEY_INDEX 0
#define RASTER_V8_PROPERTY_CALLBACK_K_SHOULD_THROW_ON_ERROR_INDEX 1
#define RASTER_V8_PROPERTY_CALLBACK_K_HOLDER_INDEX 2
#define RASTER_V8_PROPERTY_CALLBACK_K_ISOLATE_INDEX 3
#define RASTER_V8_PROPERTY_CALLBACK_K_HOLDER_V2_INDEX 4
#define RASTER_V8_PROPERTY_CALLBACK_K_RETURN_VALUE_INDEX 5
#define RASTER_V8_PROPERTY_CALLBACK_K_DATA_INDEX 6
#define RASTER_V8_PROPERTY_CALLBACK_K_THIS_INDEX 7
#define RASTER_V8_PROPERTY_CALLBACK_K_ARGS_LENGTH 8